import type { DiffFinding, DiffReport } from "./types.js";

const SEVERITY_ICON: Record<DiffFinding["severity"], string> = {
  breaking: "🚨",
  warning: "⚠️",
  info: "ℹ️",
};

function formatFinding(f: DiffFinding): string {
  const typeHint =
    f.baseline && f.candidate
      ? ` (\`${f.baseline}\` → \`${f.candidate}\`)`
      : f.baseline
        ? ` (was \`${f.baseline}\`)`
        : f.candidate
          ? ` (now \`${f.candidate}\`)`
          : "";
  const suggestion = f.suggestion ? `\n  💡 ${f.suggestion}` : "";
  return `- ${SEVERITY_ICON[f.severity]} **${f.severity.toUpperCase()}** \`${f.path}\`: ${f.message}${typeHint}${suggestion}`;
}

/** Render a Markdown report suitable for PR comments and CLI. */
export function formatMarkdownReport(report: DiffReport, title = "ContractGuard Report"): string {
  const { summary, findings, baselineLabel, candidateLabel } = report;
  const lines: string[] = [];

  lines.push(`<!-- contractguard-report -->`);
  lines.push(`## ${title}`);
  lines.push("");

  if (baselineLabel || candidateLabel) {
    lines.push(
      `Comparing **${baselineLabel ?? "baseline"}** → **${candidateLabel ?? "candidate"}**`,
    );
    lines.push("");
  }

  if (summary.total === 0) {
    lines.push("✅ No semantic API changes detected.");
    lines.push("");
    return lines.join("\n");
  }

  if (summary.breaking > 0) {
    lines.push(
      `🚨 **Breaking API Changes Detected** (${summary.breaking} breaking, ${summary.warning} warning, ${summary.info} info)`,
    );
  } else if (summary.warning > 0) {
    lines.push(
      `⚠️ **API Warnings** (${summary.warning} warning, ${summary.info} info)`,
    );
  } else {
    lines.push(`ℹ️ **Informational API Changes** (${summary.info} info)`);
  }
  lines.push("");

  const groups: DiffFinding["severity"][] = ["breaking", "warning", "info"];
  for (const severity of groups) {
    const group = findings.filter((f) => f.severity === severity);
    if (group.length === 0) continue;
    lines.push(`### ${severity.charAt(0).toUpperCase() + severity.slice(1)}`);
    lines.push("");
    for (const f of group) {
      lines.push(formatFinding(f));
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by contractguard*");
  lines.push("");
  return lines.join("\n");
}

/** Compact terminal-friendly text report. */
export function formatTextReport(report: DiffReport): string {
  const { summary, findings } = report;
  if (summary.total === 0) {
    return "No semantic API changes detected.";
  }
  const lines = [
    `Breaking: ${summary.breaking}  Warning: ${summary.warning}  Info: ${summary.info}`,
    "",
  ];
  for (const f of findings) {
    lines.push(`[${f.severity}] ${f.path}: ${f.message}`);
  }
  return lines.join("\n");
}

export type FailOn = "breaking" | "warning" | "never";

/**
 * Exit code contract:
 * - 0: clean (or failOn never)
 * - 1: warnings only (when failOn is warning)
 * - 2: breaking changes
 */
export function exitCodeForReport(report: DiffReport, failOn: FailOn = "breaking"): number {
  if (failOn === "never") return 0;
  if (report.summary.breaking > 0) return 2;
  if (failOn === "warning" && report.summary.warning > 0) return 1;
  return 0;
}
